name: Fetch Latest Stocks

on:
  schedule:
    - cron: '0 0 */15 * *'  # every 15 days
  push:                     # on any push
  workflow_dispatch:        # manual trigger

permissions:
  contents: write  # needed to allow pushing changes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock fetch script
        run: python load_data.py

      - name: Commit and push data folder only if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add data/
          git diff --cached --quiet && echo "No changes in data/" && exit 0
          
          git commit -m "Update data folder"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
